name: shellcheck

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: ShellCheck
      run: |
        find . -type f -name "*.sh" | xargs shellcheck --external-sources
